table_lookup = \
{'ICIS_ACTIVITY': 'Not available.',
 'ICIS_ACTIVITY_COMMENT': 'Not available.',
 'ICIS_ACTIVITY_CREDIT': 'Not available.',
 'ICIS_ACTIVITY_RPT': 'Not available.',
 'ICIS_COMP_MONITOR': 'Not available.',
 'ICIS_CONTACT': 'Not available.',
 'ICIS_CONTACT_ELECTRONIC_ADDR': 'Not available.',
 'ICIS_CONTACT_PHONE': 'Not available.',
 'ICIS_DEFAULT_STATISTICAL_BASE': 'Not available.',
 'ICIS_DMR': 'Not available.',
 'ICIS_DMR_EVENT': 'Not available.',
 'ICIS_DMR_FORM_PARAMETER': 'Not available.',
 'ICIS_DMR_FORM_VALUE': 'Not available.',
 'ICIS_DMR_PARAMETER': 'Not available.',
 'ICIS_DMR_VALUE': 'Not available.',
 'ICIS_ENFORCEMENT': 'Not available.',
 'ICIS_ENF_CONCLUSION': 'Not available.',
 'ICIS_ENF_CONCL_POLLUTANT': 'Not available.',
 'ICIS_ENF_CONCL_STATUTE': 'Not available.',
 'ICIS_ENF_CONCL_VIOLATION': 'Not available.',
 'ICIS_ENF_ENVIRON_JUSTICE': 'Not available.',
 'ICIS_ENF_REGIONAL_DOCKET': 'Not available.',
 'ICIS_ENF_RELIEF': 'Not available.',
 'ICIS_ENF_TYPE': 'Not available.',
 'ICIS_ENF_VIOLATION': 'Not available.',
 'ICIS_FACILITY_ADDRESS': 'Not available.',
 'ICIS_FACILITY_INTEREST': 'Not available.',
 'ICIS_FACILITY_NAICS': 'Not available.',
 'ICIS_FACILITY_POLICY': 'Not available.',
 'ICIS_FACILITY_PROGRAM': 'Not available.',
 'ICIS_FACILITY_SIC': 'Not available.',
 'ICIS_LIMIT': 'Not available.',
 'ICIS_LIMIT_MONTH': 'Not available.',
 'ICIS_LIMIT_SET': 'Not available.',
 'ICIS_LIMIT_SET_MONTH': 'Not available.',
 'ICIS_LIMIT_SET_SCHEDULE': 'Not available.',
 'ICIS_LIMIT_SET_STATUS': 'Not available.',
 'ICIS_LIMIT_TRADE_PARTNER': 'Not available.',
 'ICIS_LIMIT_VALUE': 'Not available.',
 'ICIS_NPDES_VIOLATION': 'Not available.',
 'ICIS_PERMIT': 'Not available.',
 'ICIS_PERM_ASSOCIATION': 'Not available.',
 'ICIS_PERM_BIOSOLID': 'Not available.',
 'ICIS_PERM_CAFO': 'Not available.',
 'ICIS_PERM_CAFO_ANIMAL_TYPE': 'Not available.',
 'ICIS_PERM_CAFO_BMP': 'Not available.',
 'ICIS_PERM_CAFO_CONTAINMENT': 'Not available.',
 'ICIS_PERM_CAFO_STORAGE': 'Not available.',
 'ICIS_PERM_COMP_STATUS': 'Not available.',
 'ICIS_PERM_CONSTRUCTION': 'Not available.',
 'ICIS_PERM_CSO': 'Not available.',
 'ICIS_PERM_EFFLUENT': 'Not available.',
 'ICIS_PERM_FEATURE': 'Not available.',
 'ICIS_PERM_FEATURE_CHARACTER': 'Not available.',
 'ICIS_PERM_FEATURE_COORD': 'Not available.',
 'ICIS_PERM_FEATURE_TREATMENT': 'Not available.',
 'ICIS_PERM_INDUSTRIAL': 'Not available.',
 'ICIS_PERM_NARRATIVE_CONDITION': 'Not available.',
 'ICIS_PERM_OTHER_PERMIT': 'Not available.',
 'ICIS_PERM_PRETREATMENT': 'Not available.',
 'ICIS_PERM_RNC_HISTORY': 'Not available.',
 'ICIS_PERM_SCHED_EVENT': 'Not available.',
 'ICIS_PERM_SSO': 'Not available.',
 'ICIS_PERM_STORM_WATER': 'Not available.',
 'ICIS_PERM_STORM_WATER_BODY': 'Not available.',
 'ICIS_PERM_STORM_WATER_MS4_NM': 'Not available.',
 'ICIS_PERM_TMDL': 'Not available.',
 'ICIS_PERM_TRACK_EVENT': 'Not available.',
 'ICIS_PRETREAT_PERFORM_SUMMARY': 'Not available.',
 'ICIS_SUB_ACTIVITY': 'Not available.',
 'ICIS_XREF_ACTIVITY_CONTACT': 'Not available.',
 'ICIS_XREF_ACTIVITY_FACILITY': 'Not available.',
 'ICIS_XREF_ENF_CONCL_FAC_ACT': 'Not available.',
 'ICIS_XREF_FACILITY_CONTACT': 'Not available.',
 'ICIS_XREF_PERM_FEATURE_CNTC': 'Not available.',
 'PCS_CMPL_SCHD': 'A sequence of activities with associated milestones which pertains to  a given permit.',
 'PCS_CMPL_SCHD_VIOL': 'A compliance schedule violation reflects the non-achievement of a given compliance schedule '
                       'event including the type of violation and ty pe of resolution.',
 'PCS_CODE_DESC': 'The Permit Compliance System (PCS) records milestones, events, and many other parameters in code '
                  'format. To provide text descriptions that explain the code meanings, the PCS_CODE_DESC provide s '
                  'complete information on all types of codes, and for each type, the text description of each '
                  'possible code value. For instance, permit tracking event code descriptions are accessible through '
                  'table type = 110, as annotated in the data element definition for the permit tracking event code.',
 'PCS_DMR_MEASUREMENT': 'Measurements of effluents reported on the Discharge Monitoring Report  (DMR). The violations '
                        'are detected by comparing the measurement values against the corresponding effluent limit.',
 'PCS_EFFL_LIM': 'The specific conditions set by the permit for a parameter effluent to be measured at a discharge '
                 'point.',
 'PCS_EFFL_LIM_CONCENTR': 'The concentration limits set for the effluent detailed in PCS_ EFFL_LIM.',
 'PCS_EFFL_LIM_QTY': 'The quantity limits set for the effluent detailed in PCS_ EFFL_LIM.',
 'PCS_EVIDENTIARY_HEARING_EVENT': 'An evidentiary hearing.',
 'PCS_INDUSTRIAL_USER_INFO': 'Information from the PCI_AUDIT table pertaining to industrial users, i.e. the number of '
                             'significant industrial users.',
 'PCS_INSPECTION': 'An official visit to the permit facility on a periodic basis which consists of the following '
                   'inspection types:  NPDES, Biomonitoring, Pretreatment, and Industrial User.',
 'PCS_PCI_AUDIT': 'Pretreatment Compliance Inspections (PCI) or Pretreatment Audits collect information resulting from '
                  'inspections pertaining to a Publicly Owned Treatment Works (POTWs) that receive pollutants from in '
                  'direct dischargers.',
 'PCS_PERMIT_EVENT': 'A permit event tracks the lifecycle of a permit from issuance to expiration. Examples include '
                     "'Application Received' and 'Permit Issued ', etc.",
 'PCS_PERMIT_FACILITY': 'A facility that is a discharger of pollutants from one or more point sources into the waters '
                        'of the United States.',
 'PCS_PERMIT_NPID': 'Not available.',
 'PCS_PIPE_SCHED': 'Particular discharge points at a permit facility that are governed by effluent limitations and '
                   'monitoring and submission requirements.',
 'PCS_PIPE_SCHED_LAT_LONG': 'Positional information used to locate a pipe of a permit facility.',
 'PCS_PRETREATMENT_PERF_SUMMARY': 'The minimum amount of information that characterizes a Publicly Owned Treatment '
                                  'Works (POTW).'}
